### PR TITLE
Convert from epoch to human-readable date and fix the bug of importing zones and adding records with national record names…

### PR DESCRIPTION
**Pull request by serg-sg**
If logging is enabled, then this edit allows you to display the time of the event in a human-like format.

### CODE REVIEW

**Comment by jethrocarr** [comment]
These are all great fixes @IISergII . Would you like me to merge shortly or do you have more you want to finish pushing over first?

**Comment by IISergII** [comment]
Greetings! Yes, there will be more small changes, wait a few more days. I am also preparing adaptation for PCP 7.4. I will make it a separate branch later.

**Comment by jethrocarr** [comment]
Awesome thanks! Just ping me here in comments when you're ready for review and merge.

**Comment by IISergII** [comment]
> Awesome thanks! Just ping me here in comments when you're ready for review and merge.

Done. Errors corrected. The branch for php 7.4 is ready for me. How to send to the merger? Maybe send it as a new branch too?

**Comment by IISergII** [comment]
Combined several disparate commits into one to make it easier to see the changes

**Comment by jethrocarr** [comment]
Sorry I forgot to come back to this PR! Thanks for contributing, merging in.

**Pull request merged**
